const movies = [
  {
    id: 1,
    titulo: "The Shawshank Redemption",
    genero: "Drama",
    anio: 1994,
    director: "Frank Darabont",
    likes: 2800000,
    portada: "https://m.media-amazon.com/images/M/MV5BNDY0Y2E2MjItOTRiYi00ZDQ2LWJiNDItNDQ2ZjAzYjU2YjI5XkEyXkFqcGc@._V1_FMjpg_UX674_.jpg",
  },
  {
    id: 2,
    titulo: "The Godfather",
    genero: "Crime, Drama",
    anio: 1972,
    director: "Francis Ford Coppola",
    likes: 2500000,
    portada: "https://m.media-amazon.com/images/M/MV5BZmU1YzU0NzEtMWE3OC00N2M3LTliOWMtZDRhNjU2YjlkMTZhXkEyXkFqcGc@._V1_FMjpg_UY4281_.jpg",
  },
  {
    id: 3,
    titulo: "The Dark Knight",
    genero: "Action, Crime, Drama",
    anio: 2008,
    director: "Christopher Nolan",
    likes: 2300000,
    portada: "https://m.media-amazon.com/images/M/MV5BOTAxNzI0NDE1NF5BMl5BanBnXkFtZTcwNjczMTk2Mw@@._V1_FMjpg_UX2048_.jpg",
  },
  {
    id: 4,
    titulo: "Forrest Gump",
    genero: "Drama, Romance",
    anio: 1994,
    director: "Robert Zemeckis",
    likes: 2100000,
    portada: "https://m.media-amazon.com/images/M/MV5BMGVmNzdlZmQtNzRkYS00ODU5LWJjODctYmZkYmJkN2U3MmYzXkEyXkFqcGc@._V1_FMjpg_UY5197_.jpg",
  },
  {
    id: 5,
    titulo: "Inception",
    genero: "Action, Adventure, Sci-Fi",
    anio: 2010,
    director: "Christopher Nolan",
    likes: 2100000,
    portada: "https://m.media-amazon.com/images/M/MV5BMjIyNjk1OTgzNV5BMl5BanBnXkFtZTcwOTU0OTk1Mw@@._V1_FMjpg_UX2048_.jpg",
  },
  {
    id: 6,
    titulo: "Fight Club",
    genero: "Drama",
    anio: 1999,
    director: "David Fincher",
    likes: 2000000,
    portada: "https://m.media-amazon.com/images/M/MV5BNDY1MzE3MTI0Nl5BMl5BanBnXkFtZTcwNDIwNTI5Mw@@._V1_FMjpg_UX2048_.jpg",
  },
  {
    id: 7,
    titulo: "The Matrix",
    genero: "Action, Sci-Fi",
    anio: 1999,
    director: "The Wachowskis",
    likes: 1900000,
    portada: "https://m.media-amazon.com/images/M/MV5BMDEwMGVlODAtYmU5Zi00OGM3LTg1N2YtMjEyNDMxYWY1ZGY2XkEyXkFqcGc@._V1_FMjpg_UX2160_.jpg",
  },
  {
    id: 8,
    titulo: "The Lord of the Rings: The Return of the King",
    genero: "Action, Adventure, Drama",
    anio: 2003,
    director: "Peter Jackson",
    likes: 1800000,
    portada: "https://m.media-amazon.com/images/M/MV5BNTg3Mzk3NDI0NF5BMl5BanBnXkFtZTcwNDU2MTk2Mw@@._V1_FMjpg_UY2048_.jpg",
  },
  {
    id: 9,

    titulo: "Pulp Fiction",
    genero: "Crime, Drama",
    anio: 1994,
    director: "Quentin Tarantino",
    likes: 1700000,
    portada: "https://m.media-amazon.com/images/M/MV5BNTY1MzgzOTYxNV5BMl5BanBnXkFtZTgwMDI4OTEwMjE@._V1_FMjpg_UX1600_.jpg",
  },
  {
    id: 10,
    titulo: "Schindler's List",
    genero: "Biography, Drama, History",
    anio: 1993,
    director: "Steven Spielberg",
    likes: 1600000,
    portada: "https://m.media-amazon.com/images/M/MV5BMTgwNzg3MDkxM15BMl5BanBnXkFtZTcwMzA2MDAxMw@@._V1_FMjpg_UX2048_.jpg",
  },
  {
    id: 11,
    titulo: "The Silence of the Lambs",
    genero: "Crime, Drama, Thriller",
    anio: 1991,
    director: "Jonathan Demme",
    likes: 1500000,
    portada: "https://m.media-amazon.com/images/M/MV5BNWFmYTUyN2YtODBhNy00ZjliLWJhOTMtOWMxMGQxYmMzZTIwXkEyXkFqcGc@._V1_FMjpg_UX1280_.jpg",
  },
  {
    id: 12,
    titulo: "Interstellar",
    genero: "Adventure, Drama, Sci-Fi",
    anio: 2014,
    director: "Christopher Nolan",
    likes: 1400000,
    portada: "https://m.media-amazon.com/images/M/MV5BMTc0NDQ4MjkyOF5BMl5BanBnXkFtZTgwNDE2NzUzOTE@._V1_FMjpg_UX1024_.jpg",
  },
  {
    id: 13,
    titulo: "Gladiator",
    genero: "Action, Adventure, Drama",
    anio: 2000,
    director: "Ridley Scott",
    likes: 1300000,
    portada: "https://m.media-amazon.com/images/M/MV5BZDlhOWZmODctMmJkNy00M2E0LWE3NjAtMGQ3MWQxNDk4ZTA4XkEyXkFqcGc@._V1_FMjpg_UX2160_.jpg",
  },
  {
    id: 14,
    titulo: "The Social Network",
    genero: "Biography, Drama",
    anio: 2010,
    director: "David Fincher",
    likes: 1200000,
    portada: "https://m.media-amazon.com/images/M/MV5BMTk4NTQ3MzMyMF5BMl5BanBnXkFtZTcwNDk0NTUxNA@@._V1_FMjpg_UX2048_.jpg",
  },
  {
    id: 15,
    titulo: "The Prestige",
    genero: "Drama, Mystery, Sci-Fi",
    anio: 2006,
    director: "Christopher Nolan",
    likes: 1100000,
    portada: "https://m.media-amazon.com/images/M/MV5BOTE0MzQ2NTk5MV5BMl5BanBnXkFtZTcwNjkzNDMyMw@@._V1_FMjpg_UX2048_.jpg",
  },
];

export default movies;
